### ISSUE TITLE
System.DllNotFoundException: Unable to load shared library 'lib/win/enet'

### ISSUE THREAD

**Issue by Arex360** [Speidy674/Light-Reflective-Mirror#10]
`
Starting Endpoint Service... Unhandled exception. System.DllNotFoundException: Unable to load shared library 'lib/win/enet' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: lib/win/enet: cannot read file data: Is a directory
   at ENet.Native.enet_linked_version()
   at ENet.Library.Initialize()
   at IgnoranceTransport.IgnoranceServer.ThreadWorker(Object parameters)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
Segmentation fault`

I have setup Ignorance in config.json but I get this Issue, I am using it in ubuntu

**Comment by Speidy674** [comment]
tested it on windows get a similar error, will look more into it

`Unhandled exception. System.DllNotFoundException: Unable to load DLL 'lib/win/enet' or one of its dependencies: Das angegebene Modul wurde nicht gefunden. (0x8007007E)
   at ENet.Native.enet_linked_version()
   at ENet.Library.Initialize()
   at IgnoranceTransport.IgnoranceServer.ThreadWorker(Object parameters)`
